config/routes.rb
Rails.application.routes.draw do
  resources :tabs
  resources :faqs
  resources :contacts
  resources :news

  get 'index_by_title/:id' => 'news#index_by_title'

  get 'index_by_tab/:id' => 'news#index_by_tab'

  get 'index_by_udid/:id' => 'news#index_by_udid'
  
  get 'news/search_by_title/:id' => 'news#search_by_title', as: 'news/search_by_title'
  
  get 'news/search_by_id/:id' => 'news#search_by_id', as: 'news/search_by_id'

  root to:'root#home'
  get 'test' => 'root#test'

  

  

  resources :users
  get 'search_by_login/:uid/:upw' => 'users#search_by_login'
  post 'search_by_login/:uid/:upw' => 'users#search_by_login'

  resource :session, only: [ :new, :create, :destroy ]

  wash_out :rfid
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    if params[:cros]!='y'
      #create from page query. @xieyinghua
      @faq = Faq.new(faq_params)
    else
      #create from cros post. @xieyinghua
      new_faq_params=Hash.new
      new_faq_params[:question]=params[:question]
      new_faq_params[:answer]=params[:answer]

      @faq=Faq.new(new_faq_params)
    end

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    if params[:cros]=='y'
      #update from cros post. @xieyinghua
      new_faq_params=faq_params
      new_faq_params[:question]=params[:question]
      new_faq_params[:answer]=params[:answer]

      faq_params=new_faq_params
    end

    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 問與答管理</p>

<div style='display:table;'>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#333333;width:1024px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>問與答管理</div>
  </div>
  <div style='display:table-row;'>
    <div style='display:table-cell;background:#ffffff;padding-left:5%;'>



<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



        <%= link_to '返回', faqs_path %>

    </div>
  </div>

app/views/faqs/index.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 問與答清單</p>

<div style='background:#333333;width:1024px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>問與答清單</div>

<table class="table">
  <thead>
    <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
      <th><%= t(:question, :scope=>[:activerecord,:attributes,:faq]) %></th>
      <th><%= t(:answer, :scope=>[:activerecord,:attributes,:faq]) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr style='background:#f4f4f4;color:#333333;font-size:14px;font-family:MicrosoftJhengHeiRegular;'>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= link_to '詳細', faq %></td>
        <td><%= link_to '修改', edit_faq_path(faq) %></td>
        <td><%= link_to '刪除', faq, method: :delete, data: { confirm: '確定嗎？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增問與答', new_faq_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p style='color:#ffffff;font-size:16px;font-family:PingFang-SC-Medium;'>當前位置: 管理系統 > 問與答詳細資訊</p>

<div style='display:table;'>
	<div style='display:table-row;'>
		<div style='display:table-cell;background:#333333;width:1024px;height:30px;color:#ffffff;font-size:18px;font-family:PingFang-SC-Medium;text-align:center;'>問與答詳細資訊</div>
	</div>
	<div style='display:table-row;'>
		<div style='display:table-cell;background:#ffffff;padding-left:5%;'>


<p>
  <strong><%= t(:question, :scope=>[:activerecord,:attributes,:faq]) %>:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong><%= t(:answer, :scope=>[:activerecord,:attributes,:faq]) %>:</strong>
  <%= @faq.answer %>
</p>

<%= link_to '修改', edit_faq_path(@faq) %> |
<%= link_to '返回', faqs_path %>




			<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
		</div>
	</div>
</div>