config/routes.rb
Rails.application.routes.draw do
  resources :tabs
  resources :faqs
  resources :contacts
  resources :news

  get 'index_by_title/:id' => 'news#index_by_title'

  get 'index_by_tab/:id' => 'news#index_by_tab'

  get 'index_by_udid/:id' => 'news#index_by_udid'
  
  get 'news/search_by_title/:id' => 'news#search_by_title', as: 'news/search_by_title'
  
  get 'news/search_by_id/:id' => 'news#search_by_id', as: 'news/search_by_id'

  root to:'root#home'
  get 'test' => 'root#test'

  

  

  resources :users
  get 'search_by_login/:uid/:upw' => 'users#search_by_login'
  post 'search_by_login/:uid/:upw' => 'users#search_by_login'

  resource :session, only: [ :new, :create, :destroy ]

  wash_out :rfid
end

app/views/common/_footer.html.erb
<p class="text-center" style="color:white;">
	Copyright ©2019 <%= image_tag("MiffyerLogo-2.jpg", :style=>'weight:128px;height:24px;') %>
</p>

app/views/common/_navbar.html.erb
<link href="<%= image_path('favicon.ico') %>" rel="shortcut icon" />

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <% if signed_in? %>
        <%= link_to "WEB版管理系統", root_path, id: "logo", :style=>'font-size:18px;' %>
      <% else %>
        <%= link_to "WEB版管理系統", '#', id: "logo", :style=>'font-size:18px;' %>
      <% end %>
    </div>


    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <% if signed_in? %>
          <li class="dropdown">
              <% if current_user.uid=='9999' || current_user.upower=='管理員' %>
                <li><%= link_to "會員管理", users_path %></li>
                <li><%= link_to "分類管理", tabs_path %></li>
                <li><%= link_to "文章管理", news_index_path %></li>
                <li><%= link_to "問與答管理", faqs_path %></li>
                <li><%= link_to "留言管理", contacts_path %></li>
              <% end %>
          </li>
          <li class="dropdown">
              <%= link_to " 登出#{current_user.uname} ", session_path, {:method => "delete", :class => "fa fa-power-off"} %>
          </li>
      <% else %>
        <!--<li><%= link_to "註冊", new_user_path %></li>-->
        <li><%= link_to "登入", new_session_path %></li>
      <% end %>
    </ul>


    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <% if false %>
      <div id='panel-left' class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">  
              <li>
                  <a href="#"><i class="fa fa-fw fa-edit"></i> 系統管理 </a>
              </li>      
          </ul>
      </div>
    <% end %>
    <!-- /.navbar-collapse -->
</nav>